# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds utils static library
import os

Import("env")

unitTestSrcFiles = [
    "src/AssertException.cpp",
    "src/Checks.cpp",
    "src/CurrentTest.cpp",
    "src/DeferredTestReporter.cpp",
    "src/DeferredTestResult.cpp",
    "src/MemoryOutStream.cpp",
    "src/ReportAssert.cpp",
    "src/Test.cpp",
    "src/TestDetails.cpp",
    "src/TestList.cpp",
    "src/TestReporter.cpp",
    "src/TestReporterStdout.cpp",
    "src/TestResults.cpp",
    "src/TestRunner.cpp",
    "src/TimeConstraint.cpp",
    "src/XmlTestReporter.cpp",
]

unitTestIncFiles = [
    "src/AssertException.h",
    "src/CheckMacros.h",
    "src/Checks.h",
    "src/Config.h",
    "src/CurrentTest.h",
    "src/DeferredTestReporter.h",
    "src/DeferredTestResult.h",
    "src/ExecuteTest.h",
    "src/MemoryOutStream.h",
    "src/ReportAssert.h",
    "src/Test.h",
    "src/TestDetails.h",
    "src/TestList.h",
    "src/TestMacros.h",
    "src/TestReporter.h",
    "src/TestReporterStdout.h",
    "src/TestResults.h",
    "src/TestRunner.h",
    "src/TestSuite.h",
    "src/TimeConstraint.h",
    "src/TimeHelpers.h",
    "src/UnitTest++.h",
    "src/XmlTestReporter.h",
]

if os.sys.platform == 'win32':
    unitTestSrcFiles.append( "src/Win32/TimeHelpers.cpp")
    unitTestIncFiles.append( "src/Win32/TimeHelpers.h")
else:
    unitTestSrcFiles.append( "src/Posix/TimeHelpers.cpp")
    unitTestIncFiles.append( "src/Posix/TimeHelpers.h")
    unitTestSrcFiles.append( "src/Posix/SignalTranslator.cpp")
    unitTestIncFiles.append( "src/Posix/SignalTranslator.h")

unitTestLib = env.StaticLibrary('unitTest', unitTestSrcFiles)

env.Alias("UnitTestAlias",unitTestLib)

msvc = GetOption( "MSVC" )
if msvc is not None and msvc != False and msvc != "":

    bvar = env['BUILD_VARIANT'] + '|x64'
    print( "unitTest: Generating MSVS" + env['MSVS_VERSION'] + " project files for '%s'" % bvar )
    
    env.MSVSProject(target = 'UnitTestScons' + env['MSVSPROJECTSUFFIX'],
        srcs = unitTestSrcFiles,
        incs = unitTestIncFiles,
        localincs = "",
        buildtarget = unitTestLib,
                auto_build_solution = 0,
                variant = bvar)
