#!/bin/bash -x
# The “Load” scenarios are configured to locally pick up the files written by the
# corresponding “Save” scenario (e.g. 10 writes a file and 11 picks up
#  ../10_Generic_Version_2_Save/output/state-00010.dtk).
#
# There is no comparison of output, just that the loading scenarios pick up the saved state
# and run to completion without an error.

# setlocal INPUT_SRC=/src/input
#export INPUT_SRC=C:/Users/tfischle/Github/DtkInput
export INPUT_SRC=../../../../DtkInput
set -e # exit in case of an error


cd 10_Generic_Version_2_Save
python3 --version
python3 ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I . # > ../StdOut_10_Generic_Version_2_Save.txt

cd ../11_Generic_Version_2_Load
python3 ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I . # > ../StdOut_11_Generic_Version_2_Load.txt

cd ../12_Vector_Version_2_Save
python3 ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_12_Vector_Version_2_Save.txt

cd ../13_Vector_Version_2_Load
python3 ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_13_Vector_Version_2_Load.txt

cd ../14_Malaria_Version_2_Save
python3 ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_14_Malaria_Version_2_Save.txt

cd ../15_Malaria_Version_2_Load
python3 ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_15_Malaria_Version_2_Load.txt

cd ../20_Generic_Multicore_Save
python3 ../../regression_utils.py flatten-config ./param_overrides.json
mpiexec -n 2 ../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I . # > ../StdOut_20_Generic_Multicore_Save.txt

cd ../21_Generic_Multicore_Load
python3 ../../regression_utils.py flatten-config ./param_overrides.json
mpiexec -n 2 ../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I . # > ../StdOut_21_Generic_Multicore_Load.txt

cd ../22_Nosibe_Multicore_Save
python3 ../../regression_utils.py flatten-config ./param_overrides.json
mpiexec -n 2 ../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Test # > ../StdOut_22_Nosibe_Multicore_Save.txt

cd ../23_Nosibe_Multicore_Load
python3 ../../regression_utils.py flatten-config ./param_overrides.json
mpiexec -n 2 ../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Test # > ../StdOut_23_Nosibe_Multicore_Load.txt

cd ../25_Vector_Namawala_SP_LarvalHabitat_MaskWrite
python3 ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_25_Vector_Namawala_SP_LarvalHabitat_MaskWrite.txt
python3 check_sp_larval_habitat.py

[ ! -d ../26_Vector_Namawala_SP_LarvalHabitat_ReadConfig/testing ] &&  mkdir ../26_Vector_Namawala_SP_LarvalHabitat_ReadConfig/testing
cp output/state-00050.dtk ../26_Vector_Namawala_SP_LarvalHabitat_ReadConfig/testing

[ ! -d ../27_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException/testing ] && mkdir ../27_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException/testing
cp output/state-00050.dtk ../27_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException/testing

[ ! -d ../29_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException_NotEnoughVectorParams/testing ] && mkdir ../29_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException_NotEnoughVectorParams/testing
cp output/state-00050.dtk ../29_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException_NotEnoughVectorParams/testing

cd ../26_Vector_Namawala_SP_LarvalHabitat_ReadConfig
python3 ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_26_Vector_Namawala_SP_LarvalHabitat_ReadConfig.txt
python3 check_sp_larval_habitat.py

cd ../27_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException
./run_test

cd ../28_1_Vector_Namawala_SP_LarvalHabitat_WriteSp
./run_test

[ ! -d ../28_2_Vector_Namawala_SP_LarvalHabitat_ReadSp/testing ] &&  mkdir ../28_2_Vector_Namawala_SP_LarvalHabitat_ReadSp/testing
cp output/state-00010.dtk ../28_2_Vector_Namawala_SP_LarvalHabitat_ReadSp/testing

cd ../28_2_Vector_Namawala_SP_LarvalHabitat_ReadSp
./run_test

cd ../29_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException_NotEnoughVectorParams
./run_test

cd ..
