#!/bin/bash -x
# The “Load” scenarios are configured to locally pick up the files written by the
# corresponding “Save” scenario (e.g. 10 writes a file and 11 picks up
#  ../10_Generic_Version_2_Save/output/state-00010.dtk).
#
# There is no comparison of output, just that the loading scenarios pick up the saved state
# and run to completion without an error.

# setlocal INPUT_SRC=/src/input
#export INPUT_SRC=C:/Users/tfischle/Github/DtkInput
export INPUT_SRC=/mnt/c/Users/tfischle/Github/DtkInput
set -e  #exit if one error occurs


cd 11_Generic_Version_2_Load
python ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I . # > ../StdOut_11_Generic_Version_2_Load.txt

cd ../13_Vector_Version_2_Load
python ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_13_Vector_Version_2_Load.txt

cd ../15_Malaria_Version_2_Load
python ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_15_Malaria_Version_2_Load.txt

cd ../21_Generic_Multicore_Load
python ../../regression_utils.py flatten-config ./param_overrides.json
mpiexec -n 2 ../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I . # > ../StdOut_21_Generic_Multicore_Load.txt

cd ../23_Nosibe_Multicore_Load
python ../../regression_utils.py flatten-config ./param_overrides.json
mpiexec -n 2 ../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/test # > ../StdOut_23_Nosibe_Multicore_Load.txt

# copy all dtk files created in 25_Vector_Namawala_SP_LarvalHabitat_MaskWrite
cd ../25_Vector_Namawala_SP_LarvalHabitat_MaskWrite

cp output/state-00050.dtk ../26_Vector_Namawala_SP_LarvalHabitat_ReadConfig/testing
cp output/state-00050.dtk ../27_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException/testing
cp output/state-00050.dtk ../29_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException_NotEnoughVectorParams/testing

cd ../26_Vector_Namawala_SP_LarvalHabitat_ReadConfig
python ../../regression_utils.py flatten-config ./param_overrides.json
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INPUT_SRC/Namawala # > ../StdOut_26_Vector_Namawala_SP_LarvalHabitat_ReadConfig.txt
python check_sp_larval_habitat.py

cd ../27_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException
./run_test

# copy dtk file created in 28_1_Vector_Namawala_SP_LarvalHabitat_WriteSp for load test
cd ../28_1_Vector_Namawala_SP_LarvalHabitat_WriteSp
cp output/state-00010.dtk ../28_2_Vector_Namawala_SP_LarvalHabitat_ReadSp/testing

cd ../28_2_Vector_Namawala_SP_LarvalHabitat_ReadSp
./run_test

cd ../29_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException_NotEnoughVectorParams
./run_test

cd ..
