#!/bin/bash -x

# include directories
export INCLUDE_DIR="../../../../DtkInput/Namawala"

# create config
python3 ../../regression_utils.py flatten-config ./param_overrides.json

# run eradictaion with changed config
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INCLUDE_DIR #> ../StdOut_28_Vector_Namawala_SP_LarvalHabitat_WriteReadSp_1.txt

