#!/bin/bash

# include directories
export INCLUDE_DIR="../../../../DtkInput/Namawala"

# create config
python3 ../../regression_utils.py flatten-config ./param_overrides.json

# remove species from Vector_Species_Params
python3 remove_Vector_Species_Params.py

# run eradictaion with changed config
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INCLUDE_DIR # > ..\StdOut_29_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException_NotEnoughVectorParams.txt

# print in red
echo "$(tput setaf 1)If an exception is displayed that says 'The current configuration does not comply with the state of the simulation. A habitat of type 'TEMPORARY_RAINFALL' for species 'funestus' does not exist in the simulation.', this test passed."
tput sgr0

# sleep
