# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds cajun static library

Import("env")

cajunSrcFiles = ["src/elements.cpp",
                 "src/reader.cpp",
                 "src/writer.cpp",
                 "stdafx.cpp"]

cajunIncFiles = ["include/elements.h",
                 "include/reader.h",
                 "include/writer.h",
                 "include/quick.h"]
cajunLocalInc = ["stdafx.h"]

cajunLib = env.StaticLibrary('cajun', cajunSrcFiles)



