# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds campaign static library

Import("env")

campaignSrcFiles = ["EventCoordinator.cpp",
                    "InterventionFactory.cpp",
                    "InterventionName.cpp",
                    "Interventions.cpp",
                    "NodeSetAll.cpp",
                    "NodeSetNodeList.cpp",
                    "NodeSetPolygon.cpp",
                    "NodeSetFactory.cpp",
                    "stdafx.cpp"
                    ]
campaignIncFiles = ['EventCoordinator.h',
                    'InterventionEnums.h',
                    'InterventionFactory.h',
                    'Interventions.h',
                    'NodeSet.h']
campaignLocalInc = ['stdafx.h']

campaignLib = env.StaticLibrary('campaign', campaignSrcFiles)
