# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds campaign static library

Import("env")

campaignSrcFiles = ["EventCoordinator.cpp",
                    "InterventionFactory.cpp",
                    "Interventions.cpp",
                    "InterventionValidator.cpp",
                    "NodeSetAll.cpp",
                    "NodeSetNodeList.cpp",
                    "NodeSetPolygon.cpp",
                    "NodeSetFactory.cpp",
                    "stdafx.cpp"
                    ]
campaignIncFiles = ['EventCoordinator.h',
                    'InterventionEnums.h',
                    'InterventionFactory.h',
                    'Interventions.h',
                    'InterventionValidator.h',
                    'NodeSet.h']
campaignLocalInc = ['stdafx.h']

campaignLib = env.StaticLibrary('campaign', campaignSrcFiles)

msvc = GetOption( "MSVC" )
if msvc is not None and msvc != False and msvc != "":

    bvar = env['BUILD_VARIANT'] + '|x64'
    print "Campaign: Generating MSVS" + env['MSVS_VERSION'] + " project files for '%s'" % bvar

    env.MSVSProject(target = 'CampaignScons' + env['MSVSPROJECTSUFFIX'],
		srcs = campaignSrcFiles,
		incs = campaignIncFiles,
		localincs = campaignLocalInc,
		buildtarget = campaignLib,
                auto_build_solution = 0,
                variant = bvar)
