# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds utils static library

Import("env")

snappySrcFiles = ["snappy-c.cc",
                  "snappy-sinksource.cc",
                    "snappy-stubs-internal.cc",
                    "snappy.cc"]

snappyIncFiles = ['snappy-c.h',
                  'snappy-internal.h',
                  'snappy-stubs-internal.h',
                  'snappy-sinksource.h',
                  'snappy.h']

snappyLib = env.StaticLibrary('snappy', snappySrcFiles)

