# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds utils static library

Import("env")

lz4SrcFiles = ["lib/lz4.cpp"]

lz4IncFiles = ['lib/lz4.h']

lz4Lib = env.StaticLibrary('lz4', lz4SrcFiles)

