#!/bin/bash -x

# include directories
export INCLUDE_DIR="../../../../DtkInput/Namawala"

# create config
python3 ../../regression_utils.py flatten-config ./param_overrides.json

# run eradictaion with changed config
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INCLUDE_DIR #> ../StdOut_27_Vector_Namawala_SP_LarvalHabitat_NoLarvalHabitat_ThrowException.txt

# print in red
echo "$(tput setaf 1)If an exception is displayed that says 'There is a vector population in the simulation but no vector species parameters could be loaded from the configuration.', this test passed."
tput sgr0
