#!/bin/bash

# include directories
export INCLUDE_DIR="../../../../DtkInput/Namawala"

# Change version of sp in header to cause an exception
python3 change_header.py

# run eradictaion with changed config
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INCLUDE_DIR # > ..\StdOut_30_2_Header_Version5_Check_Error_Msg.txt
