# -*- mode: python; -*-
# This Python script, SConscript, invoked by the SConscript in the upper directory,
#
# 1. builds baseReportlib static library
import os

#SVN_REV = os.popen("svn info | grep 'Last Changed Rev' | awk '{ print $4; }'").read()

Import("env")

reportSrcFiles = [
    "BaseChannelReport.cpp",
    "BaseEventReport.cpp",
    "BaseEventReportIntervalOutput.cpp",
    "BaseTextReport.cpp",
    "BaseTextReportEvents.cpp",
    "BinnedReport.cpp",
    "ChannelDataMap.cpp",
    "ReportUtilities.cpp"
]

reportIncFiles = [
    'BaseChannelReport.h',
    'BaseEventReport.h',
    'BaseEventReportIntervalOutput.h',
    'BaseTextReport.h',
    'BaseTextReportEvents.h',
    'BinnedReport.h',
    'ChannelDataMap.h',
    "ReportUtilities.h"
]

if ('Disease' in env) and ((env['Disease'] == 'Malaria') or (env['Disease'] == '')):
    reportSrcFiles.append( "ReportUtilitiesMalaria.cpp" )
    reportIncFiles.append( "ReportUtilitiesMalaria.h" )

reportLocalInc = ['stdafx.h']

reportLib = env.StaticLibrary('baseReportLib', reportSrcFiles)

msvc = GetOption( "MSVC" )
if msvc is not None and msvc != False and msvc != "":

    bvar = env['BUILD_VARIANT'] + '|x64'
    print( "baseReportLib: Generating MSVS" + env['MSVS_VERSION'] + " project files for '%s'" % bvar )
    
    env.MSVSProject(target = 'BaseReportLibScons' + env['MSVSPROJECTSUFFIX'],
        srcs = reportSrcFiles,
        incs = reportIncFiles,
        localincs = reportLocalInc,
        buildtarget = baseReportLib,
                auto_build_solution = 0,
                variant = bvar)
