#!/bin/bash -x

# include directories
export INCLUDE_DIR="../../../../DtkInput/Namawala"

# create config
python3 ../../regression_utils.py flatten-config ./param_overrides.json

# copy and rename param_overides file
cp config_flattened.json config_load_sp.json

# run python script and set parameters for serialization
python3 set_load_serialize_parameters.py

# run eradictaion and load from dtk
../../../build/x64/Release/Eradication/Eradication -C config_load_sp.json -I $INCLUDE_DIR #> ../StdOut_28_Vector_Namawala_SP_LarvalHabitat_WriteReadSp_2.txt

python3 check_sp_larval_habitat.py
