#!/bin/bash

# include directories
export INCLUDE_DIR="../../../../DtkInput/Namawala"

# create config
python3 ../../regression_utils.py flatten-config ./param_overrides.json

# run eradictaion with changed config
../../../build/x64/Release/Eradication/Eradication -C config_flattened.json -I $INCLUDE_DIR # > ..\30_Header_Version5.txt

# check header
python3 check_header.py


# sleep
